[build]
  base = "/"
  publish = "public"
  command = "npm run build"

[dev]
  framework = "#custom"
  command = "yarn run develop" 
  port = 8080 
  targetPort = 8000 
  publish = "publish" 
  autoLaunch = true 

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"  