[build]
  base = "/"
  publish = "out/"
  command = "npm run export"

[dev]
  command = "npm run dev" 
  port = 8888 
  targetPort = 3000 
  publish = "dist" 
  autoLaunch = true 

[context.deploy-preview.environment]
  NODE_ENV = "development"

[[redirects]]
  from = "/admin"
  to = "/static/admin/index.html"

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"  