[build]
  base = "/"
  publish = "out/"
  command = "npm run export"
  functions = "src/functions/"

[dev]
  framework = "#static"
  port = 8888
  publish = "out"

[[redirects]]
  from = "/"
  to = "/pt-br/home"
  force = true
  status = 301
  conditions = {Language = ["pt"]}
[[redirects]]
  from = "/"
  to = "/en-us/home"
  force = true
  status = 301

[[redirects]]
  from = "/*"
  to = "/pt-br/not-found"
  status = 404
  conditions = {Language = ["pt"]}
[[redirects]]
  from = "/*"
  to = "/en-us/not-found"
  status = 404

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"

	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''

