[build]
  base = "/"
  publish = "out/"
  command = "npm run export"
  functions = "src/functions/"

[context.deploy-preview.environment]
  ACCESS_TOKEN = "not so secret"

[[redirects]]
  from = "/*"
  to = "/blog/:splat"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  conditions = {Language = ["en"], Country = ["US"]}

[[redirects]]
  from = "/"
  to = "/en-us/home"
  conditions = {Language = ["en"]}
  status = 200

[[redirects]]
  from = "/"
  to = "/pt-br/home"
  conditions = {Language = ["pt"]}
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"

	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''

