backend:
  name: git-gateway
  branch: content
media_folder: "public/static/img"
public_folder: "/static/img"
site_url: https://marcelreis.dev
logo_url: https://marcelreis.dev/static/img/icon.png
slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Language"
        name: "lang"
        widget: "select"
        options: ["en", "pt"]

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "URL"
        name: url
        widget: "string"

      - label: "Author"
        name: "author"
        wdiget: "string"
        default: "Marcelo Reis"

      - label: "Publish Date"
        name: "date"
        widget: "datetime"

      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"

      - label: "Body"
        name: "body"
        widget: "markdown"

  - label: "Projects"
    description: "My portfolio, with all projects added"
    name: "project"
    folder: "content/projects"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - label: "Language"
        name: "lang"
        widget: "select"
        options: ["en", "es", "fr", "pt"]

      - label: "Title"
        name: "title"
        widget: "string"

      - label: "URL"
        name: "url"
        widget: "string"

      - label: "GitHub"
        name: "github"
        widget: "string"
        required: false

      - label: "Website"
        name: "website"
        widget: "string"
        required: false

      - label: "Description"
        name: "description"
        widget: "string"

      - label: "Tags"
        name: "tags"
        widget: "list"
        field: { label: Tech, name: tech, widget: string }

      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"

      - label: "Highlight"
        name: "highlight"
        widget: "select"
        options:
          - { label: "No", value: "0" }
          - { label: "Bottom", value: "1" }
          - { label: "Middle", value: "2" }
          - { label: "Top", value: "3" }

      - label: "Body"
        name: "body"
        widget: "markdown"

  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/pages/index.json"
        fields:
          - label: "SEO"
            name: "seo"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - {
                  label: "Thumbnail",
                  name: "thumbnail",
                  widget: "image",
                  default: "/logo.svg",
                }
          - { label: "Phrases", name: "phrases", widget: "list" }
          - { label: "Description", name: "description", widget: "string" }
