backend:
  name: git-gateway
  branch: master

media_folder: static/assets/posts
public_folder: assets
media_folder_relative: true
publish_mode: editorial_workflow

collections:
  - name: en-us-blog
    label: English Blog
    folder: content/en-us/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Created, name: created, widget: datetime, format: YYYY-MM-DD hh:mm:ss }
      - { label: Thumb, name: thumbnail, widget: image, required: false }
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Tags, name: tags, widget: list, default: [""] }
      - { label: Body, name: body, widget: markdown }

  - name: pt-br-blog
    label: Portuguese Blog
    folder: content/pt-br/blog
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: Created, name: created, widget: datetime, format: YYYY-MM-DD hh:mm:ss }
      - { label: Thumb, name: thumbnail, widget: image, required: false }
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Tags, name: tags, widget: list, default: [""] }
      - { label: Body, name: body, widget: markdown }

  - name: "pages"
    label: "Pages"
    files:
      - name: "about-en-us"
        label: "About en-us"
        file: "content/en-us/pages/about.md"
        fields: 
          - { label: Title, name: title, widget: string } 
          - { label: Description, name: description, widget: string }
          - { label: Thumb, name: thumbnail, widget: image, required: false }
          - { label: Body, name: body, widget: markdown }
      - name: "about-pt-br"
        label: "About pt-br"
        file: "content/pt-br/pages/about.md"
        fields: 
          - { label: Title, name: title, widget: string } 
          - { label: Description, name: description, widget: string }
          - { label: Thumb, name: thumbnail, widget: image, required: false }
          - { label: Body, name: body, widget: markdown }

      - name: "home-en-us"
        label: "Home en-us"
        file: "content/en-us/pages/home.md"
        fields: 
          - { label: Title, name: title, widget: string } 
          - { label: Description, name: description, widget: string }
          - { label: Thumb, name: thumbnail, widget: image, required: false }
          - { label: Hero Sentences, name: heroSentences, widget: list, default: [""]}
          - { label: Body, name: body, widget: markdown }
      - name: "home-pt-br"
        label: "Home pt-br"
        file: "content/pt-br/pages/home.md"
        fields: 
          - { label: Title, name: title, widget: string } 
          - { label: Description, name: description, widget: string }
          - { label: Thumb, name: thumbnail, widget: image, required: false }
          - { label: Hero Sentences, name: heroSentences, widget: list, default: [""]}
          - { label: Body, name: body, widget: markdown }

      - name: "labs-en-us"
        label: "Labs en-us"
        file: "content/en-us/pages/labs.md"
        fields: 
          - { label: Title, name: title, widget: string } 
          - { label: Description, name: description, widget: string }
          - { label: Thumb, name: thumbnail, widget: image, required: false }
          - { label: Body, name: body, widget: markdown }
      - name: "labs-pt-br"
        label: "Labs pt-br"
        file: "content/pt-br/pages/labs.md"
        fields: 
          - { label: Title, name: title, widget: string } 
          - { label: Description, name: description, widget: string }
          - { label: Thumb, name: thumbnail, widget: image, required: false }
          - { label: Body, name: body, widget: markdown }

      - name: "blog-en-us"
        label: "Blog en-us"
        file: "content/en-us/pages/blog.md"
        fields: 
          - { label: Title, name: title, widget: string } 
          - { label: Description, name: description, widget: string }
          - { label: Thumb, name: thumbnail, widget: image, required: false }
          - { label: Body, name: body, widget: markdown }
      - name: "blog-pt-br"
        label: "Blog pt-br"
        file: "content/pt-br/pages/blog.md"
        fields: 
          - { label: Title, name: title, widget: string } 
          - { label: Description, name: description, widget: string }
          - { label: Thumb, name: thumbnail, widget: image, required: false }
          - { label: Body, name: body, widget: markdown }

      - name: "not-found-en-us"
        label: "Not Found en-us"
        file: "content/en-us/pages/not-found.md"
        fields: 
          - { label: Title, name: title, widget: string } 
          - { label: Description, name: description, widget: string }
          - { label: Thumb, name: thumbnail, widget: image, required: false }
          - { label: Body, name: body, widget: markdown }
      - name: "not-found-pt-br"
        label: "Not Found pt-br"
        file: "content/pt-br/pages/not-found.md"
        fields: 
          - { label: Title, name: title, widget: string } 
          - { label: Description, name: description, widget: string }
          - { label: Thumb, name: thumbnail, widget: image, required: false }
          - { label: Body, name: body, widget: markdown }
