backend:
  name: git-gateway
  branch: master

media_folder: static/assets/posts
public_folder: assets
media_folder_relative: true
publish_mode: editorial_workflow

collections:
  - name: en-us-blog
    label: English Blog
    folder: content/en-us/blog
    create: true
    slug: '{{slug}}'
    fields:
      - { label: Created, name: created, widget: datetime, format: YYYY-MM-DD hh:mm:ss }
      - { label: Updated, name: updated, widget: datetime, format: YYYY-MM-DD hh:mm:ss }
      - { label: Cover, name: image, widget: image }
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string, pattern: ['.{,160}', "Must have up to 160 characters"] }
      - { label: Tags, name: tags, widget: list, default: [''] }
      - { label: Body, name: body, widget: markdown }

  - name: pt-br-blog
    label: Portuguese Blog
    folder: content/pt-br/blog
    create: true
    slug: '{{slug}}'
    fields:
      - { label: Created, name: created, widget: datetime, format: YYYY-MM-DD hh:mm:ss }
      - { label: Updated, name: updated, widget: datetime, format: YYYY-MM-DD hh:mm:ss }
      - { label: Cover, name: image, widget: image }
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string, pattern: ['.{,160}', "Must have up to 160 characters"] }
      - { label: Tags, name: tags, widget: list, default: [''] }
      - { label: Body, name: body, widget: markdown }
      - { label: Canonical, name: canonical, widget: "relation", collection: "en-us-blog", searchFields: ["title"], valueField: "{{ slug }}" }